export const storeProducts = [
  {
    id: 1,
    title: "Farm House",
    img: "images/pizza.webp",
    price: 10,
    info: "A pizza that goes ballistic on veggies! Check out this mouth watering overload of crunchy, crisp capsicum, succulent mushrooms and fresh tomatoes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Mexican Green Wave",
    img: "images/pizza1.webp",
    price: 12,
    info: "A pizza loaded with crunchy onions, crisp capsicum, juicy tomatoes and jalapeno with a liberal sprinkling of exotic Mexican herbs.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Deluxe Veggie",
    img: "images/pizza2.webp",
    price: 14,
    info: "For a vegetarian looking for a BIG treat that goes easy on the spices, this ones got it all. The onions, the capsicum, - with paneer and golden corn to top it all. ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Veg Extravaganza",
    img: "images/pizza3.webp",
    price: 18,
    info: "A pizza that decidedly staggers under an overload of golden corn, exotic black olives, crunchy onions, juicyfresh tomatoes and jalapeno - with extra cheese to go all around.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Chicken Golden Delight",
    img: "images/pizza4.webp",
    price: 17,
    info: "Mmm! Barbeque chicken with a topping of golden corn, exotic black olives, crunchy onions, juicyfresh tomatoes loaded with extra cheese. Worth its weight in gold",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Non Veg Supreme",
    img: "images/pizza5.webp",
    price: 20,
    info: "Bite into supreme delight of Black Olives, Onions, Grilled Mushrooms, exotic black olives, Pepper BBQ Chicken, Peri-Peri Chicken, Grilled Chicken Rashers with thin crust cheese.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Chicken Dominator",
    img: "images/pizza6.webp",
    price: 22,
    info: "Treat your taste buds with Double Pepper Barbecue Chicken, Peri-Peri Chicken, Chicken Tikka & Grilled Chicken Rashers with crunchy onions, crisp capsicum, juicy tomatoes and jalapeno",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "CHICKEN FIESTA",
    img: "images/pizza7.webp",
    price: 14,
    info: "Grilled Chicken Rashers I Peri-Peri Chicken I Onion I Capsicum with crunchy onions, crisp capsicum, juicy tomatoes and jalapeno with extra cheese overload on it to make it yummy.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Indi Chicken Tikka",
    img: "images/pizza8.webp",
    price: 15,
    info: "The wholesome flavour of tandoori masala with Chicken tikka I onion I red paprika I mint mayo with crunchy onions, crisp capsicum, juicy tomatoes and jalapeno.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Farm House",
  img: "images/pizza.webp",
  price: 10,
  info: "A pizza that goes ballistic on veggies! Check out this mouth watering overload of crunchy, crisp capsicum, succulent mushrooms and fresh tomatoes.",
  inCart: false,
  count: 0,
  total: 0,
};
